// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum EHTMLMouseButton : int
	{
		eHTMLMouseButton_Left = 0,
		eHTMLMouseButton_Right = 1,
		eHTMLMouseButton_Middle = 2,
	};
	
	public enum EMouseCursor : int
	{
		dc_user = 0,
		dc_none = 1,
		dc_arrow = 2,
		dc_ibeam = 3,
		dc_hourglass = 4,
		dc_waitarrow = 5,
		dc_crosshair = 6,
		dc_up = 7,
		dc_sizenw = 8,
		dc_sizese = 9,
		dc_sizene = 10,
		dc_sizesw = 11,
		dc_sizew = 12,
		dc_sizee = 13,
		dc_sizen = 14,
		dc_sizes = 15,
		dc_sizewe = 16,
		dc_sizens = 17,
		dc_sizeall = 18,
		dc_no = 19,
		dc_hand = 20,
		dc_blank = 21,
		dc_middle_pan = 22,
		dc_north_pan = 23,
		dc_north_east_pan = 24,
		dc_east_pan = 25,
		dc_south_east_pan = 26,
		dc_south_pan = 27,
		dc_south_west_pan = 28,
		dc_west_pan = 29,
		dc_north_west_pan = 30,
		dc_alias = 31,
		dc_cell = 32,
		dc_colresize = 33,
		dc_copycur = 34,
		dc_verticaltext = 35,
		dc_rowresize = 36,
		dc_zoomin = 37,
		dc_zoomout = 38,
		dc_help = 39,
		dc_custom = 40,
		dc_last = 41,
	};
	
	public enum EHTMLKeyModifiers : int
	{
		eHTMLKeyModifier_None = 0,
		eHTMLKeyModifier_AltDown = 1,
		eHTMLKeyModifier_CrtlDown = 2,
		eHTMLKeyModifier_ShiftDown = 4,
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4501)]
	public struct HTML_BrowserReady_t
	{
		public const int k_iCallback = 4501;
		public UInt32 m_hBrowser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4502)]
	public struct HTML_NeedsPaint_t
	{
		public const int k_iCallback = 4502;
		public UInt32 m_hBrowser;
		public string m_pBGRA;
		public UInt32 m_width;
		public UInt32 m_height;
		public UInt32 m_updateX;
		public UInt32 m_updateY;
		public UInt32 m_updateWidth;
		public UInt32 m_updateHeight;
		public UInt32 m_scrollX;
		public UInt32 m_scrollY;
		public float m_pageScale;
		public UInt32 m_pageSerial;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4503)]
	public struct HTML_StartRequest_t
	{
		public const int k_iCallback = 4503;
		public UInt32 m_hBrowser;
		public string m_pchUrl;
		public string m_pchTarget;
		public string m_pchPostData;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_isRedirect;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4504)]
	public struct HTML_CloseBrowser_t
	{
		public const int k_iCallback = 4504;
		public UInt32 m_hBrowser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4505)]
	public struct HTML_URLChanged_t
	{
		public const int k_iCallback = 4505;
		public UInt32 m_hBrowser;
		public string m_pchUrl;
		public string m_pchPostData;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_isRedirect;
		public string m_pchPageTitle;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_newNavigation;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4506)]
	public struct HTML_FinishedRequest_t
	{
		public const int k_iCallback = 4506;
		public UInt32 m_hBrowser;
		public string m_pchUrl;
		public string m_pchPageTitle;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4507)]
	public struct HTML_OpenLinkInNewTab_t
	{
		public const int k_iCallback = 4507;
		public UInt32 m_hBrowser;
		public string m_pchUrl;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4508)]
	public struct HTML_ChangedTitle_t
	{
		public const int k_iCallback = 4508;
		public UInt32 m_hBrowser;
		public string m_pchPageTitle;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4509)]
	public struct HTML_SearchResults_t
	{
		public const int k_iCallback = 4509;
		public UInt32 m_hBrowser;
		public UInt32 m_result;
		public UInt32 m_currentMatch;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4510)]
	public struct HTML_CanGoBackAndForward_t
	{
		public const int k_iCallback = 4510;
		public UInt32 m_hBrowser;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_canGoBack;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_canGoForward;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4511)]
	public struct HTML_HorizontalScroll_t
	{
		public const int k_iCallback = 4511;
		public UInt32 m_hBrowser;
		public UInt32 m_scrollMax;
		public UInt32 m_scrollCurrent;
		public float m_pageScale;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_visible;
		public UInt32 m_pageSize;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4512)]
	public struct HTML_VerticalScroll_t
	{
		public const int k_iCallback = 4512;
		public UInt32 m_hBrowser;
		public UInt32 m_scrollMax;
		public UInt32 m_scrollCurrent;
		public float m_pageScale;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_visible;
		public UInt32 m_pageSize;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4513)]
	public struct HTML_LinkAtPosition_t
	{
		public const int k_iCallback = 4513;
		public UInt32 m_hBrowser;
		public UInt32 m_X;
		public UInt32 m_Y;
		public string m_pchUrl;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_input;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_liveLink;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4514)]
	public struct HTML_JSAlert_t
	{
		public const int k_iCallback = 4514;
		public UInt32 m_hBrowser;
		public string m_pchMessage;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4515)]
	public struct HTML_JSConfirm_t
	{
		public const int k_iCallback = 4515;
		public UInt32 m_hBrowser;
		public string m_pchMessage;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4516)]
	public struct HTML_FileOpenDialog_t
	{
		public const int k_iCallback = 4516;
		public UInt32 m_hBrowser;
		public string m_pchTitle;
		public string m_pchInitialFile;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4517)]
	public struct HTML_ComboNeedsPaint_t
	{
		public const int k_iCallback = 4517;
		public UInt32 m_hBrowser;
		public string m_pBGRA;
		public UInt32 m_width;
		public UInt32 m_height;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4518)]
	public struct HTML_ShowPopup_t
	{
		public const int k_iCallback = 4518;
		public UInt32 m_hBrowser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4519)]
	public struct HTML_HidePopup_t
	{
		public const int k_iCallback = 4519;
		public UInt32 m_hBrowser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4520)]
	public struct HTML_SizePopup_t
	{
		public const int k_iCallback = 4520;
		public UInt32 m_hBrowser;
		public UInt32 m_X;
		public UInt32 m_Y;
		public UInt32 m_width;
		public UInt32 m_height;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4521)]
	public struct HTML_NewWindow_t
	{
		public const int k_iCallback = 4521;
		public UInt32 m_hBrowser;
		public string m_pchUrl;
		public UInt32 m_X;
		public UInt32 m_Y;
		public UInt32 m_width;
		public UInt32 m_height;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4522)]
	public struct HTML_SetCursor_t
	{
		public const int k_iCallback = 4522;
		public UInt32 m_hBrowser;
		public UInt32 m_eCursor;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4523)]
	public struct HTML_StatusText_t
	{
		public const int k_iCallback = 4523;
		public UInt32 m_hBrowser;
		public string m_pchStatus;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4524)]
	public struct HTML_ShowToolTip_t
	{
		public const int k_iCallback = 4524;
		public UInt32 m_hBrowser;
		public string m_pchMsg;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4525)]
	public struct HTML_UpdateToolTip_t
	{
		public const int k_iCallback = 4525;
		public UInt32 m_hBrowser;
		public string m_pchMsg;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[CallbackIdentity(4526)]
	public struct HTML_HideToolTip_t
	{
		public const int k_iCallback = 4526;
		public UInt32 m_hBrowser;
	};
	
}
