// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTSHORTCUTS_INTERFACE_VERSION001")]
	public interface IClientShortcuts
	{
		[VTableSlot(0)]
		UInt32 GetUniqueLocalAppId();
		[VTableSlot(1)]
		CGameID GetGameIDForAppID(UInt32 unAppID);
		[VTableSlot(2)]
		UInt32 GetAppIDForGameID(CGameID gameID);
		[VTableSlot(3)]
		UInt32 GetShortcutCount();
		[VTableSlot(4)]
		UInt32 GetShortcutAppIDByIndex(UInt32 uIndex);
		[VTableSlot(5)]
		string GetShortcutAppNameByIndex(UInt32 uIndex);
		[VTableSlot(6)]
		string GetShortcutExeByIndex(UInt32 uIndex);
		[VTableSlot(7)]
		UInt32 GetShortcutUserTagCountByIndex(UInt32 uIndex);
		[VTableSlot(8)]
		string GetShortcutUserTagByIndex(UInt32 uIndex, UInt32 arg1);
		[VTableSlot(9)]
		bool BIsShortcutRemoteByIndex(UInt32 uIndex);
		[VTableSlot(10)]
		bool BIsTemporaryShortcutByIndex(UInt32 uIndex);
		[VTableSlot(11)]
		bool BIsOpenVRShortcutByIndex(UInt32 uIndex);
		[VTableSlot(12)]
		string GetShortcutAppNameByAppID(UInt32 unAppID);
		[VTableSlot(13)]
		string GetShortcutExeByAppID(UInt32 unAppID);
		[VTableSlot(14)]
		string GetShortcutStartDirByAppID(UInt32 unAppID);
		[VTableSlot(15)]
		string GetShortcutIconByAppID(UInt32 unAppID);
		[VTableSlot(16)]
		string GetShortcutPathByAppID(UInt32 unAppID);
		[VTableSlot(17)]
		string GetShortcutCommandLine(UInt32 unAppID);
		[VTableSlot(18)]
		UInt32 GetShortcutUserTagCountByAppID(UInt32 unAppID);
		[VTableSlot(19)]
		string GetShortcutUserTagByAppID(UInt32 unAppID, UInt32 arg1);
		[VTableSlot(20)]
		bool BIsShortcutRemoteByAppID(UInt32 unAppID);
		[VTableSlot(21)]
		bool BIsShortcutHiddenByAppID(UInt32 unAppID);
		[VTableSlot(22)]
		bool BIsTemporaryShortcutByAppID(UInt32 unAppID);
		[VTableSlot(23)]
		bool BIsOpenVRShortcutByAppID(UInt32 unAppID);
		[VTableSlot(24)]
		bool BAllowDesktopConfigByAppID(UInt32 unAppID);
		[VTableSlot(25)]
		bool BAllowOverlayByAppID(UInt32 unAppID);
		[VTableSlot(26)]
		UInt32 GetShortcutLastPlayedTime(UInt32 unAppID);
		[VTableSlot(27)]
		UInt32 AddShortcut(string szShortcutName, string szShortcutExe, string szUnk1, string szUnk2, string szhUnk3);
		[VTableSlot(28)]
		UInt32 AddTemporaryShortcut(string arg0, string arg1, string arg2);
		[VTableSlot(29)]
		UInt32 AddOpenVRShortcut(string arg0, string arg1, string arg2);
		[VTableSlot(30)]
		void SetShortcutFromFullpath(UInt32 unAppID, string szPath);
		[VTableSlot(31)]
		void SetShortcutAppName(UInt32 unAppID, string szAppName);
		[VTableSlot(32)]
		void SetShortcutExe(UInt32 unAppID, string szExePath);
		[VTableSlot(33)]
		void SetShortcutStartDir(UInt32 unAppID, string szPath);
		[VTableSlot(34)]
		void SetShortcutIcon(UInt32 unAppID, string szIconPath);
		[VTableSlot(35)]
		void SetShortcutCommandLine(UInt32 unAppID, string szCommandLine);
		[VTableSlot(36)]
		void ClearShortcutUserTags(UInt32 unAppID);
		[VTableSlot(37)]
		void AddShortcutUserTag(UInt32 unAppID, string szTag);
		[VTableSlot(38)]
		void RemoveShortcutUserTag(UInt32 unAppID, string szTag);
		[VTableSlot(39)]
		void SetShortcutHidden(UInt32 unAppID, bool arg1);
		[VTableSlot(40)]
		void SetAllowDesktopConfig(UInt32 arg0, bool arg1);
		[VTableSlot(41)]
		void SetAllowOverlay(UInt32 unAppID, bool arg1);
		[VTableSlot(42)]
		void SetOpenVRShortcut(UInt32 arg0, bool arg1);
		[VTableSlot(43)]
		void RemoveShortcut(UInt32 unAppID);
		[VTableSlot(44)]
		void RemoveAllTemporaryShortcuts();
		[VTableSlot(45)]
		bool LaunchShortcut(UInt32 unAppID);
	};
}
