// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTUNIFIEDMESSAGES_INTERFACE_VERSION001")]
	public interface IClientUnifiedMessages
	{
		[VTableSlot(0)]
		UInt64 SendMethod(string pchServiceMethod, Byte[] pRequest, UInt32 nBuf, UInt64 ctx);
		[VTableSlot(1)]
		bool GetMethodResponseInfo(UInt64 hUmsg, ref UInt32 pnResponse, ref EResult eResult);
		[VTableSlot(2)]
		bool GetMethodResponseData(UInt64 hUmsg, Byte[] pResponseBuf, UInt32 bufSize, bool autoRelease);
		[VTableSlot(3)]
		bool ReleaseMethod(UInt64 hUmsg);
		[VTableSlot(4)]
		bool SendNotification(string pchNotification, Byte[] buf, UInt32 bufSize);
	};
}
