// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTHTTP_INTERFACE_VERSION001")]
	public interface IClientHTTP
	{
		[VTableSlot(0)]
		UInt32 CreateHTTPRequest(EHTTPMethod eHTTPRequestMethod, string pchAbsoluteURL);
		[VTableSlot(1)]
		bool SetHTTPRequestContextValue(UInt32 hRequest, UInt64 ulContextValue);
		[VTableSlot(2)]
		bool SetHTTPRequestNetworkActivityTimeout(UInt32 hRequest, UInt32 unTimeoutSeconds);
		[VTableSlot(3)]
		bool SetHTTPRequestHeaderValue(UInt32 hRequest, string pchHeaderName, string pchHeaderValue);
		[VTableSlot(4)]
		bool SetHTTPRequestGetOrPostParameter(UInt32 hRequest, string pchParamName, string pchParamValue);
		[VTableSlot(5)]
		bool SendHTTPRequest(UInt32 hRequest, ref UInt64 pCallHandle);
		[VTableSlot(6)]
		bool SendHTTPRequestAndStreamResponse(UInt32 hRequest, ref UInt64 pCallHandle);
		[VTableSlot(7)]
		bool DeferHTTPRequest(UInt32 hRequest);
		[VTableSlot(8)]
		bool PrioritizeHTTPRequest(UInt32 hRequest);
		[VTableSlot(9)]
		bool CancelHTTPRequest(UInt32 hRequest);
		[VTableSlot(10)]
		bool GetHTTPResponseHeaderSize(UInt32 hRequest, string pchHeaderName, ref UInt32 unResponseHeaderSize);
		[VTableSlot(11)]
		bool GetHTTPResponseHeaderValue(UInt32 hRequest, string pchHeaderName, Byte[] pHeaderValueBuffer, UInt32 unBufferSize);
		[VTableSlot(12)]
		bool GetHTTPResponseBodySize(UInt32 hRequest, ref UInt32 unBodySize);
		[VTableSlot(13)]
		bool GetHTTPResponseBodyData(UInt32 hRequest, Byte[] pBodyDataBuffer, UInt32 unBufferSize);
		[VTableSlot(14)]
		bool GetHTTPStreamingResponseBodyData(UInt32 hRequest, UInt32 arg1, Byte[] pBodyDataBuffer, UInt32 unBufferSize);
		[VTableSlot(15)]
		bool ReleaseHTTPRequest(UInt32 hRequest);
		[VTableSlot(16)]
		bool GetHTTPDownloadProgressPct(UInt32 hRequest, ref float pflPercentOut);
		[VTableSlot(17)]
		bool SetHTTPRequestRawPostBody(UInt32 hRequest, string pchContentType, Byte[] pubBody, UInt32 unBodyLen);
		[VTableSlot(18)]
		UInt32 CreateCookieContainer(bool arg0);
		[VTableSlot(19)]
		bool ReleaseCookieContainer(UInt32 arg0);
		[VTableSlot(20)]
		bool SetCookie(UInt32 arg0, string arg1, string arg2, string arg3);
		[VTableSlot(21)]
		bool SetHTTPRequestCookieContainer(UInt32 hRequest, UInt32 arg1);
		[VTableSlot(22)]
		bool SetHTTPRequestUserAgentInfo(UInt32 hRequest, string arg1);
		[VTableSlot(23)]
		bool SetHTTPRequestRequiresVerifiedCertificate(UInt32 hRequest, bool arg1);
		[VTableSlot(24)]
		bool SetHTTPRequestAbsoluteTimeoutMS(UInt32 hRequest, UInt32 arg1);
		[VTableSlot(25)]
		bool GetHTTPRequestWasTimedOut(UInt32 hRequest, ref bool arg1);
	};
}
