// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct ClientAppInfo
	{
		public Int32 m_iPadding;
	};
	
	public enum EParentalFeature : int
	{
		k_EParentalFeatureInvalid = 0,
		k_EParentalFeatureStore = 1,
		k_EParentalFeatureCommunity = 2,
		k_EParentalFeatureProfile = 3,
		k_EParentalFeatureFriends = 4,
		k_EParentalFeatureNews = 5,
		k_EParentalFeatureTrading = 6,
		k_EParentalFeatureSettings = 7,
		k_EParentalFeatureConsole = 8,
		k_EParentalFeatureBrowser = 9,
		k_EParentalFeatureParentalSetup = 10,
		k_EParentalFeatureLibrary = 11,
		k_EParentalFeatureTest = 12,
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct COffline_OfflineLogonTicket
	{
		public Int32 m_iPadding;
	};
	
	[InterfaceVersion("CLIENTUSER_INTERFACE_VERSION001")]
	public interface IClientUser
	{
		[VTableSlot(0)]
		Int32 GetHSteamUser();
		[VTableSlot(1)]
		void LogOn(CSteamID steamID);
		[VTableSlot(2)]
		void LogOnWithPassword(string pchLogin, string pchPassword);
		[VTableSlot(3)]
		void LogOnAndCreateNewSteamAccountIfNeeded();
		[VTableSlot(4)]
		EResult LogOnConnectionless();
		[VTableSlot(5)]
		void LogOff();
		[VTableSlot(6)]
		bool BLoggedOn();
		[VTableSlot(7)]
		ELogonState GetLogonState();
		[VTableSlot(8)]
		bool BConnected();
		[VTableSlot(9)]
		bool BTryingToLogin();
		[VTableSlot(10)]
		CSteamID GetSteamID();
		[VTableSlot(11)]
		CSteamID GetConsoleSteamID();
		[VTableSlot(12)]
		UInt32 GetClientInstanceID();
		[VTableSlot(13)]
		bool IsVACBanned(UInt32 nGameID);
		[VTableSlot(14)]
		bool SetEmail(string pchEmail);
		[VTableSlot(15)]
		bool SetConfigString(ERegistrySubTree eRegistrySubTree, string pchKey, string pchValue);
		[VTableSlot(16)]
		bool GetConfigString(ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchValue, Int32 cbValue);
		[VTableSlot(17)]
		bool SetConfigInt(ERegistrySubTree eRegistrySubTree, string pchKey, Int32 iValue);
		[VTableSlot(18)]
		bool GetConfigInt(ERegistrySubTree eRegistrySubTree, string pchKey, ref Int32 pValue);
		[VTableSlot(19)]
		bool DeleteConfigKey(ERegistrySubTree eRegistrySubTree, string pchKey);
		[VTableSlot(20)]
		bool GetConfigStoreKeyName(ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchStoreName, Int32 cbStoreName);
		[VTableSlot(21)]
		Int32 InitiateGameConnection(Byte[] pOutputBlob, Int32 cbBlobMax, CSteamID steamIDGS, CGameID gameID, UInt32 unIPServer, UInt16 usPortServer, bool bSecure);
		[VTableSlot(22)]
		Int32 InitiateGameConnectionOld(Byte[] pOutputBlob, Int32 cbBlobMax, CSteamID steamIDGS, CGameID gameID, UInt32 unIPServer, UInt16 usPortServer, bool bSecure, Byte[] pvSteam2GetEncryptionKey, Int32 cbSteam2GetEncryptionKey);
		[VTableSlot(23)]
		void TerminateGameConnection(UInt32 unIPServer, UInt16 usPortServer);
		[VTableSlot(24)]
		bool TerminateAppMultiStep(UInt32 arg0, UInt32 arg1);
		[VTableSlot(25)]
		void SetSelfAsPrimaryChatDestination();
		[VTableSlot(26)]
		bool IsPrimaryChatDestination();
		[VTableSlot(27)]
		void RequestLegacyCDKey(UInt32 iAppID);
		[VTableSlot(28)]
		bool AckGuestPass(string pchGuestPassCode);
		[VTableSlot(29)]
		bool RedeemGuestPass(string pchGuestPassCode);
		[VTableSlot(30)]
		UInt32 GetGuestPassToGiveCount();
		[VTableSlot(31)]
		UInt32 GetGuestPassToRedeemCount();
		[VTableSlot(32)]
		bool GetGuestPassToGiveInfo(UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed, StringBuilder pchRecipientAddress, Int32 cRecipientAddressSize);
		[VTableSlot(33)]
		Int32 GetGuestPassToGiveOut(UInt32 arg0);
		[VTableSlot(34)]
		Int32 GetGuestPassToRedeem(UInt32 arg0);
		[VTableSlot(35)]
		bool GetGuestPassToRedeemInfo(UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed);
		[VTableSlot(36)]
		bool GetGuestPassToRedeemSenderName(UInt32 nPassIndex, StringBuilder pchSenderName, Int32 cSenderNameSize);
		[VTableSlot(37)]
		Int32 GetNumAppsInGuestPassesToRedeem();
		[VTableSlot(38)]
		Int32 GetAppsInGuestPassesToRedeem(ref UInt32 arg0, UInt32 arg1);
		[VTableSlot(39)]
		UInt64 RequestStoreAuthURL(string arg0);
		[VTableSlot(40)]
		bool SetLanguage(string pchLanguage);
		[VTableSlot(41)]
		void TrackAppUsageEvent(CGameID gameID, Int32 eAppUsageEvent, string pchExtraInfo);
		[VTableSlot(42)]
		Int32 RaiseConnectionPriority(EConnectionPriority eConnectionPriority);
		[VTableSlot(43)]
		void ResetConnectionPriority(Int32 hRaiseConnectionPriorityPrev);
		[VTableSlot(44)]
		bool BHasCachedCredentials(string pchUnk);
		[VTableSlot(45)]
		bool SetAccountNameForCachedCredentialLogin(string pchAccountName, bool bUnk);
		[VTableSlot(46)]
		bool GetCurrentWebAuthToken(StringBuilder pchBuffer, Int32 cubBuffer, StringBuilder pchBuffer2, Int32 cubBuffer2);
		[VTableSlot(47)]
		UInt64 RequestWebAuthToken();
		[VTableSlot(48)]
		void SetLoginInformation(string pchAccountName, string pchPassword, bool bRememberPassword);
		[VTableSlot(49)]
		void SetTwoFactorCode(string arg0);
		[VTableSlot(50)]
		void ClearAllLoginInformation();
		[VTableSlot(51)]
		bool GetLanguage(StringBuilder pchLanguage, Int32 cbLanguage);
		[VTableSlot(52)]
		bool BIsCyberCafe();
		[VTableSlot(53)]
		bool BIsAcademicAccount();
		[VTableSlot(54)]
		bool BIsPortal2EducationAccount();
		[VTableSlot(55)]
		bool BIsAlienwareDemoAccount();
		[VTableSlot(56)]
		void CreateAccount(string pchAccountName, string pchNewPassword, string pchNewEmail, Int32 iQuestion, string pchNewQuestion, string pchNewAnswer);
		[VTableSlot(57)]
		UInt64 ResetPassword(string pchAccountName, string pchOldPassword, string pchNewPassword, string pchValidationCode, string pchAnswer);
		[VTableSlot(58)]
		EResult ValidatePasswordResetCodeAndSendSms(string arg0, string arg1);
		[VTableSlot(59)]
		void TrackNatTraversalStat(ref CNatTraversalStat pNatStat);
		[VTableSlot(60)]
		void TrackSteamUsageEvent(ESteamUsageEvent eSteamUsageEvent, Byte[] pubKV, UInt32 cubKV);
		[VTableSlot(61)]
		void TrackSteamGUIUsage(string arg0);
		[VTableSlot(62)]
		void SetComputerInUse();
		[VTableSlot(63)]
		bool BIsGameRunning(CGameID gameID);
		[VTableSlot(64)]
		bool BIsGameWindowReady(CGameID gameID);
		[VTableSlot(65)]
		bool BUpdateAppOwnershipTicket(UInt32 nAppID, bool bOnlyUpdateIfStale, bool bIsDepot);
		[VTableSlot(66)]
		bool RequestCustomBinary(string pszAbsolutePath, UInt32 nAppID, bool bForceUpdate, bool bAppLaunchRequest);
		[VTableSlot(67)]
		EResult GetCustomBinariesState(UInt32 unAppID, ref Int64 iUnk1, ref Int64 iUnk2);
		[VTableSlot(68)]
		EResult RequestCustomBinaries(UInt32 unAppID, bool arg1, bool arg2, ref UInt32 arg3);
		[VTableSlot(69)]
		void SetCellID(UInt32 cellID);
		[VTableSlot(70)]
		string GetUserBaseFolder();
		[VTableSlot(71)]
		bool GetUserDataFolder(CGameID gameID, StringBuilder pchBuffer, Int32 cubBuffer);
		[VTableSlot(72)]
		bool GetUserConfigFolder(StringBuilder pchBuffer, Int32 cubBuffer);
		[VTableSlot(73)]
		bool GetAccountName(StringBuilder pchAccountName, UInt32 cb);
		[VTableSlot(74)]
		bool GetAccountName(CSteamID userID, StringBuilder pchAccountName, UInt32 cb);
		[VTableSlot(75)]
		bool IsPasswordRemembered();
		[VTableSlot(76)]
		void CheckoutSiteLicenseSeat(UInt32 uUnk);
		[VTableSlot(77)]
		Int32 GetAssociatedSiteName();
		[VTableSlot(78)]
		bool RequiresLegacyCDKey(UInt32 nAppID, ref bool pbUnk);
		[VTableSlot(79)]
		bool GetLegacyCDKey(UInt32 nAppID, StringBuilder pchKeyData, Int32 cbKeyData);
		[VTableSlot(80)]
		bool SetLegacyCDKey(UInt32 nAppID, string pchKeyData);
		[VTableSlot(81)]
		bool WriteLegacyCDKey(UInt32 nAppID);
		[VTableSlot(82)]
		void RemoveLegacyCDKey(UInt32 nAppID);
		[VTableSlot(83)]
		void RequestLegacyCDKeyFromApp(UInt32 nMainAppID, UInt32 nDLCAppID);
		[VTableSlot(84)]
		bool BIsAnyGameRunning();
		[VTableSlot(85)]
		void TestAvailablePassword(Byte[] pubDigestPassword, Int32 cubDigestPassword);
		[VTableSlot(86)]
		void GetSteamGuardDetails();
		[VTableSlot(87)]
		Int32 GetTwoFactorDetails();
		[VTableSlot(88)]
		bool BHasTwoFactor();
		[VTableSlot(89)]
		void RecoverAuthenticator(string arg0, string arg1, string arg2, string arg3, string arg4);
		[VTableSlot(90)]
		void ChangePassword(string pchOldPassword, string pchNewPassword);
		[VTableSlot(91)]
		bool GetEmail(StringBuilder pchEmail, Int32 cchEmail, ref bool pbValidated);
		[VTableSlot(92)]
		void RequestForgottenPasswordEmail(string pchAccountName, string pchTriedPassword);
		[VTableSlot(93)]
		void RequestAccountResetDetails(string arg0, string arg1);
		[VTableSlot(94)]
		void FindAccountsByEmailAddress(string pchEmailAddress);
		[VTableSlot(95)]
		void FindAccountsByCdKey(string pchCdKey);
		[VTableSlot(96)]
		void GetNumAccountsWithEmailAddress(string pchEmailAddress);
		[VTableSlot(97)]
		void IsAccountNameInUse(string pchAccountName);
		[VTableSlot(98)]
		void Test_FakeConnectionTimeout();
		[VTableSlot(99)]
		bool RunInstallScript(UInt32 pAppIDs, string pchUnk, bool bUninstall);
		[VTableSlot(100)]
		UInt32 IsInstallScriptRunning();
		[VTableSlot(101)]
		bool GetInstallScriptState(StringBuilder pchDescription, UInt32 cchDescription, ref UInt32 punNumSteps, ref UInt32 punCurrStep);
		[VTableSlot(102)]
		bool SpawnProcess(string lpApplicationName, string lpCommandLine, UInt32 dwCreationFlags, string lpCurrentDirectory, CGameID gameID, string pchGameName, UInt32 uUnk);
		[VTableSlot(103)]
		UInt32 GetAppOwnershipTicketLength(UInt32 nAppID);
		[VTableSlot(104)]
		UInt32 GetAppOwnershipTicketData(UInt32 nAppID, Byte[] pvBuffer, UInt32 cbBufferLength);
		[VTableSlot(105)]
		UInt32 GetAppOwnershipTicketExtendedData(UInt32 nAppID, Byte[] pvBuffer, UInt32 cbBufferLength, ref UInt32 piAppId, ref UInt32 piSteamId, ref UInt32 piSignature, ref UInt32 pcbSignature);
		[VTableSlot(106)]
		Int32 GetMarketingMessageCount();
		[VTableSlot(107)]
		bool GetMarketingMessage(Int32 cMarketingMessage, ref UInt64 gidMarketingMessageID, StringBuilder pubMsgUrl, Int32 cubMessageUrl, ref EMarketingMessageFlags eMarketingMssageFlags);
		[VTableSlot(108)]
		UInt32 GetAuthSessionTicket(Byte[] pMyAuthTicket, Int32 cbMaxMyAuthTicket, ref UInt32 pcbAuthTicket);
		[VTableSlot(109)]
		EBeginAuthSessionResult BeginAuthSession(Byte[] pTheirAuthTicket, Int32 cbTicket, CSteamID steamID);
		[VTableSlot(110)]
		void EndAuthSession(CSteamID steamID);
		[VTableSlot(111)]
		void CancelAuthTicket(UInt32 hAuthTicket);
		[VTableSlot(112)]
		EUserHasLicenseForAppResult IsUserSubscribedAppInTicket(CSteamID steamID, UInt32 appID);
		[VTableSlot(113)]
		void AdvertiseGame(CGameID gameID, CSteamID steamIDGameServer, UInt32 unIPServer, UInt16 usPortServer);
		[VTableSlot(114)]
		UInt64 RequestEncryptedAppTicket(Byte[] pUserData, Int32 cbUserData);
		[VTableSlot(115)]
		bool GetEncryptedAppTicket(Byte[] pTicket, Int32 cbMaxTicket, ref UInt32 pcbTicket);
		[VTableSlot(116)]
		Int32 GetGameBadgeLevel(Int32 nSeries, bool bFoil);
		[VTableSlot(117)]
		Int32 GetPlayerSteamLevel();
		[VTableSlot(118)]
		void SetAccountLimited(bool bAccountLimited);
		[VTableSlot(119)]
		bool BIsAccountLimited();
		[VTableSlot(120)]
		void SetAccountCommunityBanned(bool bBanned);
		[VTableSlot(121)]
		bool BIsAccountCommunityBanned();
		[VTableSlot(122)]
		void SetLimitedAccountCanInviteFriends(bool bCanInviteFriends);
		[VTableSlot(123)]
		bool BLimitedAccountCanInviteFriends();
		[VTableSlot(124)]
		void SendValidationEmail();
		[VTableSlot(125)]
		bool BGameConnectTokensAvailable();
		[VTableSlot(126)]
		Int32 NumGamesRunning();
		[VTableSlot(127)]
		CGameID GetRunningGameID(Int32 iGame);
		[VTableSlot(128)]
		Int32 GetRunningGamePID(Int32 arg0);
		[VTableSlot(129)]
		UInt32 GetAccountSecurityPolicyFlags();
		[VTableSlot(130)]
		void RequestPasswordChangeEmail(string arg0, Int32 arg1);
		[VTableSlot(131)]
		void ChangePasswordWithCode(string pchOldPassword, string pchCode, string pchNewPassword);
		[VTableSlot(132)]
		void RequestEmailChange(string arg0, string arg1);
		[VTableSlot(133)]
		void ChangeEmailWithCode(string arg0, string arg1, string arg2, string arg3, string arg4);
		[VTableSlot(134)]
		void SetClientStat(EClientStat eStat, Int64 llValue, UInt32 nAppID, UInt32 nDepotID, UInt32 nCellID);
		[VTableSlot(135)]
		void VerifyPassword(string pchPassword);
		[VTableSlot(136)]
		bool BSupportUser();
		[VTableSlot(137)]
		bool BNeedsSSANextSteamLogon();
		[VTableSlot(138)]
		void ClearNeedsSSANextSteamLogon();
		[VTableSlot(139)]
		bool BIsAppOverlayEnabled(CGameID gameID);
		[VTableSlot(140)]
		bool BOverlayIgnoreChildProcesses(CGameID arg0);
		[VTableSlot(141)]
		bool BIsBehindNAT();
		[VTableSlot(142)]
		UInt32 GetMicroTxnAppID(UInt64 gidTransID);
		[VTableSlot(143)]
		UInt64 GetMicroTxnOrderID(UInt64 gidTransID);
		[VTableSlot(144)]
		bool BGetMicroTxnPrice(UInt64 gidTransID, ref CAmount pamtTotal, ref CAmount pamtTax, ref bool pbVat, ref CAmount pUnk);
		[VTableSlot(145)]
		Int32 GetMicroTxnLineItemCount(UInt64 gidTransID);
		[VTableSlot(146)]
		bool BGetMicroTxnLineItem(UInt64 gidTransID, UInt32 unLineItem, ref CAmount pamt, ref UInt32 punQuantity, StringBuilder pchDescription, UInt32 cubDescriptionLength, ref Int32 pRecurringTimeUnit, Byte[] pRecurringFrequency, ref CAmount pRecurringAmount, ref bool pbUnk);
		[VTableSlot(147)]
		bool BIsSandboxMicroTxn(UInt64 gidTransID, ref bool pbSandbox);
		[VTableSlot(148)]
		bool BMicroTxnRequiresCachedPmtMethod(UInt64 gidTransID, ref bool pbRequired);
		[VTableSlot(149)]
		UInt64 AuthorizeMicroTxn(UInt64 gidTransID, EMicroTxnAuthResponse eMicroTxnAuthResponse);
		[VTableSlot(150)]
		bool BGetWalletBalance(ref bool pbHasWallet, ref CAmount pamtBalance, ref CAmount arg2);
		[VTableSlot(151)]
		UInt64 RequestMicroTxnInfo(UInt64 gidTransID);
		[VTableSlot(152)]
		bool BMicroTxnRefundable(UInt64 gidTransID);
		[VTableSlot(153)]
		bool BGetAppMinutesPlayed(UInt32 nAppId, ref Int32 pnForever, ref Int32 pnLastTwoWeeks);
		[VTableSlot(154)]
		UInt32 GetAppLastPlayedTime(UInt32 nAppId);
		[VTableSlot(155)]
		UInt32 GetAppUpdateDisabledSecondsRemaining(UInt32 arg0);
		[VTableSlot(156)]
		bool BGetGuideURL(UInt32 uAppID, StringBuilder pchURL, UInt32 cchURL);
		[VTableSlot(157)]
		bool BPromptToVerifyEmail();
		[VTableSlot(158)]
		bool BPromptToChangePassword();
		[VTableSlot(159)]
		bool BAccountExtraSecurity();
		[VTableSlot(160)]
		bool BAccountShouldShowLockUI();
		[VTableSlot(161)]
		Int32 GetCountAuthedComputers();
		[VTableSlot(162)]
		bool BSteamGuardNewMachineNotification();
		[VTableSlot(163)]
		UInt32 GetSteamGuardEnabledTime();
		[VTableSlot(164)]
		bool GetSteamGuardHistoryEntry(Int32 iEntryIndex, ref UInt32 puTimestamp, ref UInt32 puIP, ref bool pbIsRemembered, StringBuilder pchGeolocInfo, Int32 cchGeolocInfo, StringBuilder pchUnk, Int32 cbUnk);
		[VTableSlot(165)]
		void SetSteamGuardNewMachineDialogResponse(bool bIsApproved, bool bIsWizardComplete);
		[VTableSlot(166)]
		void SetPhoneIsVerified(bool arg0);
		[VTableSlot(167)]
		bool BIsPhoneVerified();
		[VTableSlot(168)]
		void SetPhoneIsIdentifying(bool arg0);
		[VTableSlot(169)]
		bool BIsPhoneIdentifying();
		[VTableSlot(170)]
		void SetPhoneIsRequiringVerification(bool arg0);
		[VTableSlot(171)]
		bool BIsPhoneRequiringVerification();
		[VTableSlot(172)]
		void ChangeTwoFactorAuthOptions(Int32 eOption);
		[VTableSlot(173)]
		void Set2ndFactorAuthCode(string pchAuthCode, bool bDontRememberComputer);
		[VTableSlot(174)]
		void SetUserMachineName(string pchMachineName);
		[VTableSlot(175)]
		bool GetUserMachineName(StringBuilder pchMachineName, Int32 cbMachineName);
		[VTableSlot(176)]
		bool GetEmailDomainFromLogonFailure(StringBuilder pchEmailDomain, Int32 cbEmailDomain);
		[VTableSlot(177)]
		bool BIsSubscribedApp(UInt32 nAppId);
		[VTableSlot(178)]
		UInt32 GetSubscribedApps(ref UInt32 arg0, UInt32 arg1, bool arg2);
		[VTableSlot(179)]
		UInt64 RegisterActivationCode(string pchActivationCode);
		[VTableSlot(180)]
		void AckSystemIM(UInt64 arg0);
		[VTableSlot(181)]
		UInt64 RequestSpecialSurvey(UInt32 uSurveyId);
		[VTableSlot(182)]
		UInt64 SendSpecialSurveyResponse(UInt32 uSurveyId, Byte[] pubData, UInt32 cubData);
		[VTableSlot(183)]
		void RequestNotifications();
		[VTableSlot(184)]
		bool GetAppOwnershipInfo(UInt32 unAppId, ref UInt32 pRTime32Created, ref UInt32 unk, StringBuilder pchCountry);
		[VTableSlot(185)]
		void SendGameWebCallback(UInt32 unAppId, string szData);
		[VTableSlot(186)]
		void StopStreaming(bool arg0, Int32 arg1);
		[VTableSlot(187)]
		bool BIsStreamingUIToRemoteDevice();
		[VTableSlot(188)]
		bool BIsCurrentlyNVStreaming();
		[VTableSlot(189)]
		void RequestStopNVStreaming();
		[VTableSlot(190)]
		void OnBigPictureStreamingResult(bool arg0, Byte[] arg1);
		[VTableSlot(191)]
		void OnBigPictureStreamingDone();
		[VTableSlot(192)]
		void OnBigPictureStreamRestarting();
		[VTableSlot(193)]
		void LockParentalLock();
		[VTableSlot(194)]
		bool UnlockParentalLock(string pchUnk);
		[VTableSlot(195)]
		bool BIsParentalLockEnabled();
		[VTableSlot(196)]
		bool BIsParentalLockLocked();
		[VTableSlot(197)]
		void BlockApp(UInt32 unAppID);
		[VTableSlot(198)]
		void UnblockApp(UInt32 unAppID);
		[VTableSlot(199)]
		bool BIsAppBlocked(UInt32 unAppID);
		[VTableSlot(200)]
		bool BIsAppInBlockList(UInt32 unAppID);
		[VTableSlot(201)]
		void BlockFeature(EParentalFeature eParentalFeature);
		[VTableSlot(202)]
		void UnblockFeature(EParentalFeature eParentalFeature);
		[VTableSlot(203)]
		bool BIsFeatureBlocked(EParentalFeature eParentalFeature);
		[VTableSlot(204)]
		bool BIsFeatureInBlockList(EParentalFeature eParentalFeature);
		[VTableSlot(205)]
		UInt32 GetParentalUnlockTime();
		[VTableSlot(206)]
		bool BGetRecoveryEmail(StringBuilder arg0, Int32 arg1);
		[VTableSlot(207)]
		void RequestParentalRecoveryEmail();
		[VTableSlot(208)]
		bool BGetSerializedParentalSettings(ref CUtlBuffer pBuffer);
		[VTableSlot(209)]
		bool BSetParentalSettings(ref CUtlBuffer pBuffer);
		[VTableSlot(210)]
		bool BDisableParentalSettings();
		[VTableSlot(211)]
		bool BGetParentalWebToken(ref CUtlBuffer arg0, ref CUtlBuffer arg1);
		[VTableSlot(212)]
		bool BCanLogonOfflineMode();
		[VTableSlot(213)]
		EResult LogOnOfflineMode();
		[VTableSlot(214)]
		EResult ValidateOfflineLogonTicket(string pchUnk);
		[VTableSlot(215)]
		bool BGetOfflineLogonTicket(string pchUnk, ref COffline_OfflineLogonTicket pTicket);
		[VTableSlot(216)]
		void UploadLocalClientLogs();
		[VTableSlot(217)]
		void SetAsyncNotificationEnabled(UInt32 arg0, bool arg1);
		[VTableSlot(218)]
		bool BIsOtherSessionPlaying(ref UInt32 arg0);
		[VTableSlot(219)]
		bool BKickOtherPlayingSession();
		[VTableSlot(220)]
		void PerformAccountRecoveryUpload();
		[VTableSlot(221)]
		bool BIsAccountLockedDown();
		[VTableSlot(222)]
		void RemoveAppTag(CGameID arg0, string arg1);
		[VTableSlot(223)]
		void AddAppTag(CGameID arg0, string arg1);
		[VTableSlot(224)]
		void SetAppHidden(CGameID arg0, bool arg1);
		[VTableSlot(225)]
		UInt64 RequestAccountLinkInfo();
	};
}
