// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum EPackageStatus : int
	{
	};
	
	[InterfaceVersion("CLIENTBILLING_INTERFACE_VERSION001")]
	public interface IClientBilling
	{
		[VTableSlot(0)]
		bool PurchaseWithActivationCode(string pchActivationCode);
		[VTableSlot(1)]
		bool HasActiveLicense(UInt32 arg0);
		[VTableSlot(2)]
		bool GetLicenseInfo(UInt32 nLicenseIndex, ref UInt32 pRTime32Created, ref UInt32 pRTime32NextProcess, ref Int32 pnMinuteLimit, ref Int32 pnMinutesUsed, ref EPaymentMethod pePaymentMethod, ref UInt32 punFlags, ref Int32 pnTerritoryCode, StringBuilder prgchPurchaseCountryCode);
		[VTableSlot(3)]
		void EnableTestLicense(UInt32 unPackageID);
		[VTableSlot(4)]
		void DisableTestLicense(UInt32 unPackageID);
		[VTableSlot(5)]
		UInt32 GetAppsInPackage(UInt32 unPackageID, ref UInt32 puIds, UInt32 uMaxIds);
		[VTableSlot(6)]
		UInt64 RequestFreeLicenseForApps(ref UInt32 puIds, UInt32 smth);
	};
}
