// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public enum EDepotBuildStatus : int
	{
		k_EDepotBuildStatusInvalid = 0,
		k_EDepotBuildStatusProcessingConfig = 1,
		k_EDepotBuildStatusBuildingFileList = 2,
		k_EDepotBuildStatusProcessingData = 3,
		k_EDepotBuildStatusUploadingData = 4,
		k_EDepotBuildStatusCompleted = 5,
		k_EDepotBuildStatusFailed = 6,
	};
	
	public enum EStatusDepotVersion : int
	{
		k_EStatusDepotVersionInvalid = 0,
		k_EStatusDepotVersionDisabled = 1,
		k_EStatusDepotVersionAvailable = 2,
		k_EStatusDepotVersionCurrent = 3,
	};
	
	[InterfaceVersion("CLIENTDEPOTBUILDER_INTERFACE_VERSION001")]
	public interface IClientDepotBuilder
	{
		[VTableSlot(0)]
		bool BGetDepotBuildStatus(UInt64 arg0, ref EDepotBuildStatus arg1, ref UInt64 arg2, ref UInt64 arg3);
		[VTableSlot(1)]
		Int32 VerifyChunkStore(UInt32 arg0, UInt32 arg1, string arg2);
		[VTableSlot(2)]
		Int32 DownloadDepot(UInt32 arg0, UInt32 arg1, UInt64 arg2, UInt64 arg3, UInt64 arg4, UInt32 arg5);
		[VTableSlot(3)]
		Int32 StartDepotBuild(UInt32 arg0, UInt32 arg1, UInt32 arg2, string arg3);
		[VTableSlot(4)]
		Int32 CommitAppBuild(UInt32 arg0, UInt32 arg1, ref UInt32 arg2, ref UInt64 arg3, string arg4, string arg5);
	};
}
