// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public interface IClientBluetoothManager
	{
		[VTableSlot(0)]
		void SetDiscovering(bool arg0);
		[VTableSlot(1)]
		Int32 EnumerateDevice(UInt32 arg0);
		[VTableSlot(2)]
		Int32 GetDeviceType(string arg0);
		[VTableSlot(3)]
		string GetDeviceName(string arg0);
		[VTableSlot(4)]
		bool IsConnected(string arg0);
		[VTableSlot(5)]
		bool IsPaired(string arg0);
		[VTableSlot(6)]
		bool Pair(string arg0);
		[VTableSlot(7)]
		bool UnPair(string arg0);
		[VTableSlot(8)]
		bool Connect(string arg0);
		[VTableSlot(9)]
		bool Disconnect(string arg0);
		[VTableSlot(10)]
		bool IsAvailable();
	};
}
