// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("CLIENTPARENTALSETTINGS_INTERFACE_VERSION001")]
	public interface IClientParentalSettings
	{
		[VTableSlot(0)]
		bool BIsParentalLockEnabled();
		[VTableSlot(1)]
		bool BIsParentalLockLocked();
		[VTableSlot(2)]
		bool BIsAppBlocked(UInt32 unAppID);
		[VTableSlot(3)]
		bool BIsAppInBlockList(UInt32 unAppID);
		[VTableSlot(4)]
		bool BIsFeatureBlocked(EParentalFeature eParentalFeature);
		[VTableSlot(5)]
		bool BIsFeatureInBlockList(EParentalFeature eParentalFeature);
		[VTableSlot(6)]
		bool BGetSerializedParentalSettings(ref CUtlBuffer arg0);
		[VTableSlot(7)]
		bool BGetRecoveryEmail(StringBuilder pchEmailAddr, Int32 cbEmailAddr);
	};
}
