// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	public interface ISteamVideo002
	{
		[VTableSlot(0)]
		void GetVideoURL(UInt32 appId);
		[VTableSlot(1)]
		bool IsBroadcasting(ref Int32 pnNumViewers);
		[VTableSlot(2)]
		Int32 GetOPFSettings(UInt32 arg0);
		[VTableSlot(3)]
		Int32 GetOPFStringForApp(UInt32 arg0, StringBuilder arg1, ref Int32 arg2);
	};
}
