// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMAPPLIST_INTERFACE_VERSION001")]
	public interface ISteamAppList001
	{
		[VTableSlot(0)]
		UInt32 GetNumInstalledApps();
		[VTableSlot(1)]
		UInt32 GetInstalledApps(ref UInt32 apps, UInt32 appsMax);
		[VTableSlot(2)]
		Int32 GetAppName(UInt32 appId, StringBuilder pchAppNameOut, Int32 nameMax);
		[VTableSlot(3)]
		Int32 GetAppInstallDir(UInt32 appId, StringBuilder pchAppPathOut, Int32 pathMax);
		[VTableSlot(4)]
		Int32 GetAppBuildId(UInt32 appId);
	};
}
