// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMVIDEO_INTERFACE_V002")]
	public interface ISteamVideo002
	{
		[VTableSlot(0)]
		void GetVideoURL(UInt32 appId);
		[VTableSlot(1)]
		bool IsBroadcasting(ref Int32 pnNumViewers);
		[VTableSlot(2)]
		void GetOPFSettings(UInt32 unVideoAppID);
		[VTableSlot(3)]
		bool GetOPFStringForApp(UInt32 unVideoAppID, StringBuilder pchBuffer, ref Int32 pnBufferSize);
	};
}
