// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("STEAMUGC_INTERFACE_VERSION008")]
	public interface ISteamUGC008
	{
		[VTableSlot(0)]
		UInt64 CreateQueryUserUGCRequest(UInt32 unAccountID, EUserUGCList eListType, EUGCMatchingUGCType eMatchingUGCType, EUserUGCListSortOrder eSortOrder, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(1)]
		UInt64 CreateQueryAllUGCRequest(EUGCQuery eQueryType, EUGCMatchingUGCType eMatchingeMatchingUGCTypeFileType, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage);
		[VTableSlot(2)]
		UInt64 CreateQueryUGCDetailsRequest(ref UInt64 arg0, UInt32 arg1);
		[VTableSlot(3)]
		UInt64 SendQueryUGCRequest(UInt64 handle);
		[VTableSlot(4)]
		bool GetQueryUGCResult(UInt64 handle, UInt32 index, ref SteamUGCDetails_t pDetails);
		[VTableSlot(5)]
		bool GetQueryUGCPreviewURL(UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3);
		[VTableSlot(6)]
		bool GetQueryUGCMetadata(UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3);
		[VTableSlot(7)]
		bool GetQueryUGCChildren(UInt64 handle, UInt32 arg1, ref UInt64 arg2, UInt32 arg3);
		[VTableSlot(8)]
		bool GetQueryUGCStatistic(UInt64 handle, UInt32 arg1, EItemStatistic arg2, ref UInt32 arg3);
		[VTableSlot(9)]
		UInt32 GetQueryUGCNumAdditionalPreviews(UInt64 handle, UInt32 arg1);
		[VTableSlot(10)]
		bool GetQueryUGCAdditionalPreview(UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6, ref EItemPreviewType arg7);
		[VTableSlot(11)]
		UInt32 GetQueryUGCNumKeyValueTags(UInt64 handle, UInt32 arg1);
		[VTableSlot(12)]
		bool GetQueryUGCKeyValueTag(UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6);
		[VTableSlot(13)]
		bool ReleaseQueryUGCRequest(UInt64 handle);
		[VTableSlot(14)]
		bool AddRequiredTag(UInt64 handle, string pTagName);
		[VTableSlot(15)]
		bool AddExcludedTag(UInt64 handle, string pTagName);
		[VTableSlot(16)]
		bool SetReturnKeyValueTags(UInt64 handle, bool arg1);
		[VTableSlot(17)]
		bool SetReturnLongDescription(UInt64 handle, bool bReturnLongDescription);
		[VTableSlot(18)]
		bool SetReturnMetadata(UInt64 handle, bool arg1);
		[VTableSlot(19)]
		bool SetReturnChildren(UInt64 handle, bool arg1);
		[VTableSlot(20)]
		bool SetReturnAdditionalPreviews(UInt64 handle, bool arg1);
		[VTableSlot(21)]
		bool SetReturnTotalOnly(UInt64 handle, bool bReturnTotalOnly);
		[VTableSlot(22)]
		bool SetLanguage(UInt64 handle, string arg1);
		[VTableSlot(23)]
		bool SetAllowCachedResponse(UInt64 handle, UInt32 unMaxAgeSeconds);
		[VTableSlot(24)]
		bool SetCloudFileNameFilter(UInt64 handle, string pMatchCloudFileName);
		[VTableSlot(25)]
		bool SetMatchAnyTag(UInt64 handle, bool bMatchAnyTag);
		[VTableSlot(26)]
		bool SetSearchText(UInt64 handle, string pSearchText);
		[VTableSlot(27)]
		bool SetRankedByTrendDays(UInt64 handle, UInt32 unDays);
		[VTableSlot(28)]
		bool AddRequiredKeyValueTag(UInt64 handle, string arg1, string arg2);
		[VTableSlot(29)]
		UInt64 RequestUGCDetails(UInt64 nPublishedFileID, UInt32 unMaxAgeSeconds);
		[VTableSlot(30)]
		UInt64 CreateItem(UInt32 nConsumerAppId, EWorkshopFileType eFileType);
		[VTableSlot(31)]
		UInt64 StartItemUpdate(UInt32 nConsumerAppId, UInt64 nPublishedFileID);
		[VTableSlot(32)]
		bool SetItemTitle(UInt64 handle, string pchTitle);
		[VTableSlot(33)]
		bool SetItemDescription(UInt64 handle, string pchDescription);
		[VTableSlot(34)]
		bool SetItemUpdateLanguage(UInt64 handle, string arg1);
		[VTableSlot(35)]
		bool SetItemMetadata(UInt64 handle, string arg1);
		[VTableSlot(36)]
		bool SetItemVisibility(UInt64 handle, ERemoteStoragePublishedFileVisibility eVisibility);
		[VTableSlot(37)]
		bool SetItemTags(UInt64 updateHandle, ref SteamParamStringArray_t pTags);
		[VTableSlot(38)]
		bool SetItemContent(UInt64 handle, string pszContentFolder);
		[VTableSlot(39)]
		bool SetItemPreview(UInt64 handle, string pszPreviewFile);
		[VTableSlot(40)]
		bool RemoveItemKeyValueTags(UInt64 handle, string arg1);
		[VTableSlot(41)]
		bool AddItemKeyValueTag(UInt64 handle, string arg1, string arg2);
		[VTableSlot(42)]
		bool AddItemPreviewFile(UInt64 handle, string arg1, EItemPreviewType arg2);
		[VTableSlot(43)]
		bool AddItemPreviewVideo(UInt64 handle, string arg1);
		[VTableSlot(44)]
		bool UpdateItemPreviewFile(UInt64 handle, UInt32 arg1, string arg2);
		[VTableSlot(45)]
		bool UpdateItemPreviewVideo(UInt64 handle, UInt32 arg1, string arg2);
		[VTableSlot(46)]
		bool RemoveItemPreview(UInt64 handle, UInt32 arg1);
		[VTableSlot(47)]
		UInt64 SubmitItemUpdate(UInt64 handle, string pchChangeNote);
		[VTableSlot(48)]
		EItemUpdateStatus GetItemUpdateProgress(UInt64 handle, ref UInt64 punBytesProcessed, ref UInt64 punBytesTotal);
		[VTableSlot(49)]
		UInt64 SetUserItemVote(UInt64 arg0, bool arg1);
		[VTableSlot(50)]
		UInt64 GetUserItemVote(UInt64 arg0);
		[VTableSlot(51)]
		UInt64 AddItemToFavorites(UInt32 arg0, UInt64 arg1);
		[VTableSlot(52)]
		UInt64 RemoveItemFromFavorites(UInt32 arg0, UInt64 arg1);
		[VTableSlot(53)]
		UInt64 SubscribeItem(UInt64 nPublishedFileID);
		[VTableSlot(54)]
		UInt64 UnsubscribeItem(UInt64 nPublishedFileID);
		[VTableSlot(55)]
		UInt32 GetNumSubscribedItems();
		[VTableSlot(56)]
		UInt32 GetSubscribedItems(ref UInt64 pvecPublishedFileID, UInt32 cMaxEntries);
		[VTableSlot(57)]
		UInt32 GetItemState(UInt64 arg0);
		[VTableSlot(58)]
		bool GetItemInstallInfo(UInt64 nPublishedFileID, ref UInt64 punSizeOnDisk, StringBuilder pchFolder, UInt32 cchFolderSize, ref bool pbLegacyItem);
		[VTableSlot(59)]
		bool GetItemDownloadInfo(UInt64 arg0, ref UInt64 arg1, ref UInt64 arg2);
		[VTableSlot(60)]
		bool DownloadItem(UInt64 arg0, bool arg1);
		[VTableSlot(61)]
		bool BInitWorkshopForGameServer(UInt32 arg0, string arg1);
		[VTableSlot(62)]
		void SuspendDownloads(bool arg0);
		[VTableSlot(63)]
		UInt64 StartPlaytimeTracking(ref UInt64 publishedFields, UInt32 numPublishedFields);
		[VTableSlot(64)]
		UInt64 StopPlaytimeTracking(ref UInt64 publishedFields, UInt32 numPublishedFields);
		[VTableSlot(65)]
		UInt64 StopPlaytimeTrackingForAllItems();
	};
}
