// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;
using Steam4NET.Attributes;

namespace Steam4NET
{

	[InterfaceVersion("SteamController006")]
	public interface ISteamController006
	{
		[VTableSlot(0)]
		bool Init();
		[VTableSlot(1)]
		bool Shutdown();
		[VTableSlot(2)]
		void RunFrame();
		[VTableSlot(3)]
		Int32 GetConnectedControllers(ref UInt64 hControllers);
		[VTableSlot(4)]
		bool ShowBindingPanel(UInt64 hController);
		[VTableSlot(5)]
		UInt64 GetActionSetHandle(string actionSetName);
		[VTableSlot(6)]
		void ActivateActionSet(UInt64 hController, UInt64 hAction);
		[VTableSlot(7)]
		UInt64 GetCurrentActionSet(UInt64 hController);
		[VTableSlot(8)]
		void ActivateActionSetLayer(UInt64 hController, UInt64 arg1);
		[VTableSlot(9)]
		void DeactivateActionSetLayer(UInt64 hController, UInt64 arg1);
		[VTableSlot(10)]
		void DeactivateAllActionSetLayers(UInt64 hController);
		[VTableSlot(11)]
		Int32 GetActiveActionSetLayers(UInt64 hController, ref UInt64 arg1);
		[VTableSlot(12)]
		UInt64 GetDigitalActionHandle(string actionName);
		[VTableSlot(13)]
		ControllerDigitalActionData_t GetDigitalActionData(UInt64 controllerHandle, UInt64 actionHandle);
		[VTableSlot(14)]
		Int32 GetDigitalActionOrigins(UInt64 hController, UInt64 hActionSet, UInt64 hAction, ref EControllerActionOrigin eOrigin);
		[VTableSlot(15)]
		UInt64 GetAnalogActionHandle(string actionName);
		[VTableSlot(16)]
		ControllerAnalogActionData_t GetAnalogActionData(UInt64 controllerHandle, UInt64 actionHandle);
		[VTableSlot(17)]
		Int32 GetAnalogActionOrigins(UInt64 hController, UInt64 hActionSet, UInt64 hAction, ref EControllerActionOrigin eOrigin);
		[VTableSlot(18)]
		void StopAnalogActionMomentum(UInt64 hController, UInt64 hAction);
		[VTableSlot(19)]
		void TriggerHapticPulse(UInt64 hController, ESteamControllerPad eTargetPad, UInt16 usDurationMicroSec);
		[VTableSlot(20)]
		void TriggerRepeatedHapticPulse(UInt64 hController, ESteamControllerPad arg1, UInt16 durationMs, UInt16 offMs, UInt16 repeat, UInt32 flags);
		[VTableSlot(21)]
		void TriggerVibration(UInt64 hController, UInt16 leftSpeed, UInt16 rightSpeed);
		[VTableSlot(22)]
		void SetLEDColor(UInt64 hController, Byte R, Byte G, Byte B, UInt32 flags);
		[VTableSlot(23)]
		Int32 GetGamepadIndexForController(UInt64 hController);
		[VTableSlot(24)]
		UInt64 GetControllerForGamepadIndex(Int32 idx);
		[VTableSlot(25)]
		ControllerMotionData_t GetMotionData(UInt64 controllerHandle);
		[VTableSlot(26)]
		bool ShowDigitalActionOrigins(UInt64 hController, UInt64 hAction, float scale, float XPos, float YPos);
		[VTableSlot(27)]
		bool ShowAnalogActionOrigins(UInt64 hController, UInt64 hAction, float scale, float XPos, float YPos);
		[VTableSlot(28)]
		string GetStringForActionOrigin(EControllerActionOrigin eOrigin);
		[VTableSlot(29)]
		string GetGlyphForActionOrigin(EControllerActionOrigin eOrigin);
	};
}
